config/routes.rb
Rails.application.routes.draw do
  resources :channels

  resources :shippings

  resources :sales

  resources :clients do 
    collection do
      get "csv"
    end
  end

  root :to => "dashboard#index"
  
  devise_scope :user do
    get '/login' => "users/sessions#new"
    delete '/logout' => "users/sessions#destroy"
  end
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users

  resources :brands

  resources :products do
    collection do 
      get "sku"
      get "csv"
    end
  end

  resources :sections

  resources :sub_categories do
    get "sections"
  end

  resources :categories do
    get "sub_categories"
  end

  resources :orders do
    post "send_contract"
    post "send_confirmation"
    post "send_offer"
    collection do
      get "csv"
    end
  end

  resources :suppliers do 
    get "show_products"
    get "show_orders"
    post "send_condition"
    collection do 
      get "csv"
    end
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @channels = Channel.all
    respond_with(@channels)
  end

  def show
    respond_with(@channel)
  end

  def new
    @channel = Channel.new
    respond_with(@channel)
  end

  def edit
  end

  def create
    @channel = Channel.new(channel_params)
    @channel.save
    respond_with(@channel)
  end

  def update
    @channel.update(channel_params)
    respond_with(@channel)
  end

  def destroy
    @channel.destroy
    respond_with(@channel)
  end

  private
    def set_channel
      @channel = Channel.find(params[:id])
    end

    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= simple_form_for @channel, :html => { :class => 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| %>
    <%= f.input :name %>
  <div class="form-group">
    <div class='col-sm-offset-3 col-sm-9'>
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  channels_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/channels/edit.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/index.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.id %></td>
          <td><%= channel.name %></td>
        <td><%=l channel.created_at, format: :long %></td>
        <td>
          <%= link_to channel_path(channel), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_channel_path(channel), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to channel_path(channel), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_channel_path,
            :class => 'btn btn-primary' %>

app/views/channels/new.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/show.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @channel.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              channels_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_channel_path(@channel), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              channel_path(@channel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>