config/routes.rb
Rails.application.routes.draw do
  resources :channels

  resources :shippings

  resources :sales

  resources :clients do 
    collection do
      get "csv"
    end
  end

  root :to => "dashboard#index"
  
  devise_scope :user do
    get '/login' => "users/sessions#new"
    delete '/logout' => "users/sessions#destroy"
  end
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users

  resources :brands

  resources :products do
    collection do 
      get "sku"
      get "csv"
    end
  end

  resources :sections

  resources :sub_categories do
    get "sections"
  end

  resources :categories do
    get "sub_categories"
  end

  resources :orders do
    post "send_contract"
    post "send_confirmation"
    post "send_offer"
    collection do
      get "csv"
    end
  end

  resources :suppliers do 
    get "show_products"
    get "show_orders"
    post "send_condition"
    collection do 
      get "csv"
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by
    ]
  )

  belongs_to :channel

  validates :first_name, presence: true
  validates :last_name, presence: true

  self.per_page = 25

  scope :search_query, lambda {|query|
    return nil  if query.blank?
    terms = query.to_s.downcase.split(/\s+/)
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "LOWER(clients.first_name) LIKE ?",
          "LOWER(clients.last_name) LIKE ?",
          "LOWER(clients.email) LIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("clients.created_at #{ direction }")
    when /^name_/
      order("LOWER(clients.last_name) #{ direction }, LOWER(clients.first_name) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Nombre (a-z)', 'name_asc'],
      ['Fecha registro (descendiente)', 'created_at_desc'],
      ['Fecha registro (ascendiente)', 'created_at_asc'],
    ]
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |client|
        csv << client.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @filterrific = initialize_filterrific(
      Client,
      params[:filterrific],
      select_options: {
        sorted_by: Client.options_for_sorted_by,
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [:search_query, :sorted_by],
    ) or return
    @clients = @filterrific.find.page(params[:page])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    respond_with(@client)
  end

  def new
    @client = Client.new
    respond_with(@client)
  end

  def edit
  end

  def create
    @client = Client.new(client_params)
    @client.save
    respond_with(@client)
  end

  def update
    @client.update(client_params)
    respond_with(@client)
  end

  def destroy
    @client.destroy
    respond_with(@client)
  end

  def csv
    @clients = Client.all
    respond_to do |format|
      format.csv { send_data @clients.to_csv }
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :phone)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client, :html => { :class => 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.association :channel, label_method: :name, value_method: :id, include_blank: false %>
  <div class="form-group">
    <div class='col-sm-offset-3 col-sm-9'>
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  clients_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/clients/_list.html.erb
<%- model_class = Client -%>
<div id="filterrific_results">
  <div class="well well-sm">
    <%= page_entries_info clients %>
    <%= render_filterrific_spinner %>
    <%= link_to 'Reset', reset_filterrific_url, :class => 'btn btn-default btn-xs pull-right' %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:first_name) %></th>
        <th><%= model_class.human_attribute_name(:last_name) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:phone) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.id %></td>
            <td><%= client.first_name %></td>
            <td><%= client.last_name %></td>
            <td><%= client.email %></td>
            <td><%= client.phone %></td>
          <td><%=l client.created_at, format: :long %></td>
          <td>
            <%= link_to client_path(client), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
              <%= glyph 'info-sign' %>
            <%- end -%>
            <%= link_to edit_client_path(client), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
              <%= glyph 'pencil' %>
            <%- end -%>
            <%= link_to client_path(client), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
            <%- end -%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="row">
  <div class="page-header col-md-8">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <div class="col-md-4">
    <%= link_to "CSV", csv_clients_path(format: "csv"), class: 'btn btn-default pull-right' %>
  </div>
</div>
<div class="well">
  <div class="row">
    <%= form_for_filterrific @filterrific do |f| %>
      <div class="col-md-4">
        <%= f.label 'Buscar' %>
        <%= f.text_field :search_query, placeholder: 'Buscar', class: 'filterrific-periodically-observed form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label 'Ordenar' %>
        <%= f.select :sorted_by, @filterrific.select_options[:sorted_by], {}, class: 'filterrific-periodically-observed form-control' %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'clients/list', clients: @clients %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary' %>

app/views/clients/index.js.erb
<% js = escape_javascript render(partial: 'clients/list', locals: { clients: @clients }) %>
$("#filterrific_results").html("<%= js %>");

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @client.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @client.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @client.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @client.phone %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              clients_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_client_path(@client), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              client_path(@client),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/clients/show_products.html.erb
<%- model_class = Client -%>
<%- model_product = Product -%>
<div class="page-header">
  <h1>Productos de <%= @client.first_name %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>SKU</th>
      <th>Retiro</th>
      <th>Nombre</th>
      <th>Marca</th>
      <th>Precio</th>
      <th>Estado</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @client.products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.order.id %></td>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.price %></td>
        <td><%= product.status %></td>
        <td>
          <%= link_to edit_product_path(product) do %>
            <button class="btn btn-default btn-xs pull-right" type="button">
              <span class="glyphicon glyphicon-edit"></span>
            </button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Atrás', clients_path, :class => 'btn btn-primary' %>