config/routes.rb
Rails.application.routes.draw do
  resources :channels

  resources :shippings

  resources :sales

  resources :clients do 
    collection do
      get "csv"
    end
  end

  root :to => "dashboard#index"
  
  devise_scope :user do
    get '/login' => "users/sessions#new"
    delete '/logout' => "users/sessions#destroy"
  end
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users

  resources :brands

  resources :products do
    collection do 
      get "sku"
      get "csv"
    end
  end

  resources :sections

  resources :sub_categories do
    get "sections"
  end

  resources :categories do
    get "sub_categories"
  end

  resources :orders do
    post "send_contract"
    post "send_confirmation"
    post "send_offer"
    collection do
      get "csv"
    end
  end

  resources :suppliers do 
    get "show_products"
    get "show_orders"
    post "send_condition"
    collection do 
      get "csv"
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :filter_by_status
    ]
  )

  belongs_to :category
  belongs_to :sub_category
  belongs_to :section
  belongs_to :order
  belongs_to :brand
  belongs_to :sale

  validates :name, presence: true
  validates :category, presence: true
  validates :sub_category, presence: true
  validates :section, presence: true
  validates :sku, presence: true
  validates :percentage_consignation, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  self.per_page = 25

  scope :search_query, lambda {|query|
    return nil  if query.blank?
    terms = query.to_s.downcase.split(/\s+/)
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    num_or_conditions = 3
    joins("LEFT JOIN brands ON brands.id = products.brand_id")
    .where(
      terms.map {
        or_clauses = [
          "LOWER(products.name) LIKE ?",
          "LOWER(products.sku) LIKE ?",
          "LOWER(brands.name) LIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("products.created_at #{ direction }")
    when /^name_/
      order("LOWER(products.name) #{ direction }")
    when /^brand_name_/
      order("LOWER(brands.name) #{ direction }").joins(:brand)
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :filter_by_status, lambda { |status| status.nil? ? nil : where(status: status)}

  def full_category
    "/#{self.category.name}/#{self.sub_category.name}/#{self.section.name}/"
  end

  def self.sku_id sku
    p = Product.where("sku like ?", "#{sku}%").order("length(sku) DESC").order("sku DESC")[0]
    if p
      p.sku.split('-')[-1].to_i + 1
    else
      1
    end
  end

  def self.options_for_sorted_by
    [
      ['Nombre (a-z)', 'name_asc'],
      ['Fecha registro (descendiente)', 'created_at_desc'],
      ['Fecha registro (ascendiente)', 'created_at_asc'],
      ['Marca (a-z)', 'brand_name_asc']
    ]
  end

  def self.status_options
    [
      ['', ''],
      ['Recibido', 'revieved'],
      ['Aceptado', 'accepted'],
      ['Procesado', 'processed'],
      ['Fotografiado', 'photographed'],
      ['Vendido', 'sold'],
      ['Rechazado', 'rejected'],
    ]
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      select_options: {
        sorted_by: Product.options_for_sorted_by,
        filter_by_status: Product.status_options,
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [:search_query, :sorted_by, :filter_by_status],
    ) or return
    @products = @filterrific.find.page(params[:page])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js { render :on_create }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sku
    sku = params[:sku]
    if sku
      sku_id = Product.sku_id(sku)
      respond_to do |format|
        format.json { render json: {id: sku_id}}
      end
    else
      respond_to do |format|
        format.json { render json: {id: null}}
      end
    end
  end

  def csv
    @products = Product.all
    respond_to do |format|
      format.csv { send_data @products.to_csv }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:observation, :status, :category_id, :sub_category_id, :section_id, :name, :sku, :brand_id, :new_foreign_price, :new_chilean_price, :used_foreign_price, :used_chilean_price, :reference_price, :price, :order_id, :weight, :description, :height, :width, :depth, :is_consignation, :percentage_consignation)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active bindInformation"><a href="#">Información básica</a></li>
    <li role="presentation" class="bindPrice"><a href="#">Precios</a></li>
    <li role="presentation" class="bindCategory"><a href="#">Categorías</a></li>
    <li role="presentation" class="bindSale"><a href="#">Ventas</a></li>
  </ul>
  <div class="row" id="basicInformation">
    <div class="col-md-4">
      <%= f.input :name, as: :string %>
      <%= f.input :description %>
      <%= f.input :observation %>
    </div>
    <div class="col-md-4">
      <%= f.input :status do %>
        <%= f.select :status, Product.status_options, {include_blank: false}, class: 'form-control' %>
      <% end %>
      <%= f.association :brand, label_method: :name, value_method: :id, include_blank: :true %>
      <%= f.association :order, label_method: :product_display, value_method: :id, include_blank: true %>
      <%= f.input :is_consignation %>
      <%= f.input :percentage_consignation %>
    </div>
    <div class="col-md-4">
      <%= f.input :weight %>
      <%= f.input :height %>
      <%= f.input :width %>
      <%= f.input :depth %>
    </div>
  </div>

  <div class="row hidden" id="price">
    <div class="col-md-4">
      <%= f.input :new_foreign_price %>
      <%= f.input :used_foreign_price %>
    </div>
    <div class="col-md-4">
      <%= f.input :new_chilean_price %>
      <%= f.input :used_chilean_price %>
    </div>
    <div class="col-md-4">
      <%= f.input :reference_price %>
      <%= f.input :price %>
    </div>
  </div>

  <div class="row hidden" id="category">
    <div class="col-md-6">
      <%= f.association :category, label_method: :name, value_method: :id, include_blank: true %>
      <%= f.association :sub_category, label_method: :name, value_method: :id, include_blank: true %>
    </div>
    <div class="col-md-6">
      <%= f.association :section, label_method: :name, value_method: :id, include_blank: true %>
      <%= f.input :sku %>
    </div>
  </div>

  <div class="row hidden" id="sale">
    <div class="col-md-6">
      <%= f.association :sale, label_method: :human_display, value_method: :id, include_blank: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                :back, :class => 'btn' %>
  </div>
<% end %>

app/views/products/_list.html.erb
<%- model_class = Product -%>
<div id="filterrific_results">
  <div class="well well-sm">
    <%= page_entries_info products %>
    <%= render_filterrific_spinner %>
    <%= link_to 'Reset', reset_filterrific_url, :class => 'btn btn-default btn-xs pull-right' %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:sku) %></th>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:brand_id) %></th>
        <th><%= model_class.human_attribute_name(:price) %></th>
        <th><%= model_class.human_attribute_name(:status) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.sku %></td>
          <td><%= product.name %></td>
          <td><%= product.brand ? product.brand.name : '-' %></td>
          <td><%= product.price %></td>
          <td><%= product.status %></td>
          <td>
            <div class="dropdown pull-right">
              <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cog"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a>Vender</a></li>
                <li role="presentation"><%= link_to 'Ver', product, role: "menuitem", tabindex: "-1" %></li>
                <li role="presentation"><%= link_to 'Editar', edit_product_path(product), role: "menuitem", tabindex: "-1" %></li>
                <li role="presentation"><%= link_to 'Eliminar', product, method: :delete, data: { confirm: '¿Estás seguro?' }, role: "menuitem", tabindex: "-1" %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="center-block" align="center">
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/products/_product_short_row.html.erb
<tr>
  <td><%= product.sku %></td>
  <td><%= product.full_category %></td>
  <td><%= product.name %></td>
  <td><span class="glyphicon glyphicon-ok"></span></td>
  <td><button class="btn btn-success btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"><span class="glyphicon glyphicon-ok"></span></button></td>
  <td>
    <div class="dropdown pull-right">
      <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Editar', edit_product_path(product), role: "menuitem", tabindex: "-1" %></li>
        <li role="presentation"><%= link_to 'Eliminar', product_path(product), method: :delete, role: "menuitem", tabindex: "-1", data: { confirm: '¿Estás seguro?' } %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="row">
  <div class="page-header col-md-8">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <div class="col-md-4">
    <%= link_to "CSV", csv_products_path(format: "csv"), class: 'btn btn-default pull-right' %>
  </div>
</div>

<div class="well">
  <div class="row">
    <%= form_for_filterrific @filterrific do |f| %>
      <div class="col-md-4">
        <%= f.label 'Buscar' %>
        <%= f.text_field :search_query, placeholder: 'Buscar', class: 'filterrific-periodically-observed form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label 'Ordenar' %>
        <%= f.select :sorted_by, @filterrific.select_options[:sorted_by], {}, class: 'filterrific-periodically-observed form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label 'Estado' %>
        <%= f.select :filter_by_status, @filterrific.select_options[:filter_by_status], {}, class: 'filterrific-periodically-observed form-control' %>
      </div>
    <% end %>
  </div>
</div>


<%= render 'list', products: @products %> 

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/index.js.erb
<% js = escape_javascript render(partial: 'products/list', locals: { products: @products }) %>
$("#filterrific_results").html("<%= js %>");

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/on_create.js.erb
<% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |message| %>
      $("#alert").append($("<div alert-danger>").html("<%= message.html_safe %>"))
    <% end %>
<% else %>
    $("#alert").html($("<p class='alert alert-success add-product-notification'>Producto creado</p>"));
    $("#alert").removeClass('hidden');

    $('<%= "#order-table-#{@product.order.id}" %> tr:last').after("<%= escape_javascript(render 'products/product_short_row', :product => @product) %>")
    $("#addNewProductModal").modal("hide")
    $('#new_product')[0].reset()
    $('#product_sub_category_id').prop('disabled', true)
    $('#product_section_id').prop('disabled', true)

    setTimeout(function () {
      $('.add-product-notification').slideUp('slow', function() {
        $(this).html('');
      });
    }, 2000);
<% end %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @product.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observation) %>:</strong></dt>
  <dd><%= @product.observation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @product.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @product.category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sub_category_id) %>:</strong></dt>
  <dd><%= @product.sub_category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:section_id) %>:</strong></dt>
  <dd><%= @product.section_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sku) %>:</strong></dt>
  <dd><%= @product.sku %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand_id) %>:</strong></dt>
  <dd><%= @product.brand_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_foreign_price) %>:</strong></dt>
  <dd><%= @product.new_foreign_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_chilean_price) %>:</strong></dt>
  <dd><%= @product.new_chilean_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:used_foreign_price) %>:</strong></dt>
  <dd><%= @product.used_foreign_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:used_chilean_price) %>:</strong></dt>
  <dd><%= @product.used_chilean_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reference_price) %>:</strong></dt>
  <dd><%= @product.reference_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @product.order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @product.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @product.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:width) %>:</strong></dt>
  <dd><%= @product.width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:depth) %>:</strong></dt>
  <dd><%= @product.depth %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>