config/routes.rb
Rails.application.routes.draw do
  resources :channels

  resources :shippings

  resources :sales

  resources :clients do 
    collection do
      get "csv"
    end
  end

  root :to => "dashboard#index"
  
  devise_scope :user do
    get '/login' => "users/sessions#new"
    delete '/logout' => "users/sessions#destroy"
  end
  
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :users

  resources :brands

  resources :products do
    collection do 
      get "sku"
      get "csv"
    end
  end

  resources :sections

  resources :sub_categories do
    get "sections"
  end

  resources :categories do
    get "sub_categories"
  end

  resources :orders do
    post "send_contract"
    post "send_confirmation"
    post "send_offer"
    collection do
      get "csv"
    end
  end

  resources :suppliers do 
    get "show_products"
    get "show_orders"
    post "send_condition"
    collection do 
      get "csv"
    end
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :shipping
  belongs_to :channel

  has_many :products

  def human_display
    "#{self.client.first_name} #{self.client.last_name} #{self.created_at}"
  end

  # def save sale_params
  #   #self.amount =  Product.where(id: sale_params[:product_ids]).sum(:price)
  #   super
  # end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sales = Sale.all
    respond_with(@sales)
  end

  def show
    respond_with(@sale)
  end

  def new
    @sale = Sale.new
    respond_with(@sale)
  end

  def edit
  end

  def create
    @sale = Sale.new(sale_params)
    @sale.save
    respond_with(@sale)
  end

  def update
    @sale.update(sale_params)
    respond_with(@sale)
  end

  def destroy
    @sale.destroy
    respond_with(@sale)
  end

  private
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def sale_params
      params.require(:sale).permit(:channel_id, :amount, :client_id, :shipping_id, :product_ids => [])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for @sale, :html => { :class => 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f| %>
    <%= f.association :channel %>
    <%= f.association :client, label_method: :first_name, value_method: :id, include_blank: true %>
    <%= f.association :shipping, label_method: :address, value_method: :id, include_blank: true %>
    <%= f.association :products, input_html: { class: 'multiselect' } %>
  <div class="form-group">
    <div class='col-sm-offset-3 col-sm-9'>
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sales_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:channel) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:client_id) %></th>
      <th><%= model_class.human_attribute_name(:shipping_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.id %></td>
          <td><%= sale.channel.name %></td>
          <td><%= sale.amount %></td>
          <td><%= sale.client_id %></td>
          <td><%= sale.shipping_id %></td>
        <td><%=l sale.created_at, format: :long %></td>
        <td>
          <%= link_to sale_path(sale), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_sale_path(sale), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to sale_path(sale), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:channel) %></dt>
      <dd><pre class="prettyprint"><%= @sale.channel %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amount) %></dt>
      <dd><pre class="prettyprint"><%= @sale.amount %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_id) %></dt>
      <dd><pre class="prettyprint"><%= @sale.client_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:shipping_id) %></dt>
      <dd><pre class="prettyprint"><%= @sale.shipping_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>